"""init changed project

Revision ID: 29083b5c5dcf
Revises: f9fde1cdc91e
Create Date: 2025-09-29 09:05:54.384838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29083b5c5dcf'
down_revision: Union[str, Sequence[str], None] = 'f9fde1cdc91e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'state')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('state', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
